Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -38,12 +38,7 @@ Testeslocais:
     - sleep 5
     - RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8000/api/produto)
     - echo "HTTP Response $RESPONSE"
-    - if [[ "$RESPONSE" -ge 200 && "$RESPONSE" -lt 300 ]]; then
-        echo "Request succeeded with status code $RESPONSE."
-      else
-        echo "Request failed with status code $RESPONSE."
-        exit 1
-      fi
+    - if [[ "$RESPONSE" -ge 200 && "$RESPONSE" -lt 300 ]]; then echo "Request succeeded with status code $RESPONSE."; else echo "Request failed with status code $RESPONSE."; exit 1; fi
     - source venv/bin/activate
     - echo "Running schemathesis tests..."
     - schemathesis run --base-url=http://localhost:8000/api docs/clogistica.yml \
